// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nccbcdwvmcpujhigqwzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jY2JjZHd2bWNwdWpoaWdxd3p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODAwMDMsImV4cCI6MjA3MjY1NjAwM30.xCddXp7532C3ocuxdPzQr1YDlZ2TOErpTKzJrEESdmY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});